# Site settings
title: esnext
email: esnext@brian-donovan.com
description: "News, updates, and tidbits about the esnext project."
baseurl: ""
url: "https://esnext.github.io"
twitter_username: esnextjs
github_username:  esnext

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
future: false

defaults:
  -
    scope:
      path: ""
      type: "post"
    values:
      author: "Brian Donovan"
